const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
for(const file of ['editorial-rules','text-structure','academic-review','detector','reference-check'])require('../js/'+file+'.js');
const E=globalThis.ZeroIADetector;
const sample='Es importante destacar que el procedimiento requiere revisión.';
const first=E.analyzeDocument(sample);
assert.deepEqual(first,E.analyzeDocument(sample));
assert.equal(first.authorship.probability,null);
assert.equal(first.status,'limited_sample');
assert.equal(E.analyzeDocument('!!!').status,'no_prose');
assert.equal(E.analyzeDocument('Referencias\nGómez, A. (2020). Método.').status,'no_body');
const raw='\ufeff👩‍💻 Texto\u200b.';
assert.equal(E.stripInvisibleCharacters(raw),raw.slice(1));
assert.equal(E.detectInvisibleWatermarks(raw).hasWatermark,false);
assert.equal(E.applySuggestion(sample,first,0),'El procedimiento requiere revisión.');
assert.throws(()=>E.applySuggestion(sample+' ',first,0));
const metadata={title:['Método experimental acústico'],author:[{family:'Gómez'}],issued:{'date-parts':[[2020]]}};
assert.equal(ZeroIAReferenceCheck.compare('Pérez (2023). Otro título.',metadata).status,'possible_mismatch');
assert.equal(ZeroIAReferenceCheck.compare('Gómez (2020). Método experimental acústico.',metadata).status,'manual_review');
const ui=fs.readFileSync('js/app.js','utf8'),html=fs.readFileSync('index.html','utf8');
vm.runInThisContext(ui.slice(0,ui.indexOf('/**')));
assert.equal(escapeHTML('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');
for(const [,id] of ui.matchAll(/document\.getElementById\("([^"]+)"\)/g))assert.ok(html.includes(`id="${id}"`)||ui.includes(`id="${id}"`),id);
(async()=>{
 const workers=[];
 class Worker {constructor(){workers.push(this);}postMessage(data){this.data=data;}terminate(){this.terminated=true;}}
 const ctx=vm.createContext({Worker,setTimeout,clearTimeout,Error});
 vm.runInContext(fs.readFileSync('js/analysis-client.js','utf8'),ctx);
 const p=ctx.ZeroIAAnalysisClient.analyze('text');
 ctx.ZeroIAAnalysisClient.cancel();
 await assert.rejects(p,{name:'AbortError'});
 assert.ok(workers[0].terminated);
 const q=ctx.ZeroIAAnalysisClient.analyze('text');
 const w=workers[1];w.onmessage({data:{id:w.data.id,result:first}});
 assert.deepEqual(await q,first);
 const broken=ctx.ZeroIAAnalysisClient.analyze('text');workers[2].onerror();
 await assert.rejects(broken,/motor/);
 console.log('Browser contracts passed: evidence, source integrity, DOI, DOM, cancellation and recovery.');
})().catch(e=>{console.error(e);process.exitCode=1;});
