const assert = require('node:assert/strict');
for (const file of ['editorial-rules','text-structure','academic-review','detector']) require('../js/'+file+'.js');
const A=globalThis.ZeroIAAcademic,S=globalThis.ZeroIAStructure;
const multi='Según Holm, Kumar y Rohde, 2012, el método necesita revisión.\nReferencias\nHolm, M., Kumar, V. y Rohde, C. (2012). Método.';
const c=A.academicReview(multi).citations;
assert.equal(c.citations[0].key,'holm:2012');
assert.equal(c.citations[0].status,'internal_match');
assert.equal(A.academicReview('Según Pérez y Gómez (2020), hay evidencia.\nReferencias\nPérez, A. (2020). Estudio.').citations.citations[0].status,'internal_match');
const empty='Introducción\nSegún Holm, Kumar y Rohde, 2012, hay evidencia.\nResultados\nConclusiones\nBibliografía';
const progress=A.preflight(empty,{stage:'progress'}),final=A.preflight(empty,{stage:'final'});
assert.ok(progress.findings.some(f=>f.code==='empty_bibliography'&&f.severity==='high'));
assert.ok(progress.findings.some(f=>f.code==='empty_section'&&f.severity==='info'));
assert.ok(final.findings.some(f=>f.code==='empty_section'&&f.severity==='high'));
assert.equal(final.ready,null);
assert.equal(A.preflight(empty).stage,'progress');
const method='El CLV se calcula en un año.\nLos datos sintéticos demuestran la validez empírica.\nEl objetivo es demostrar p < 0,05.\nSe exige una silueta superior a 0,5.\nSe usará ANOVA o Chi-cuadrado.';
const findings=A.preflight(method).findings;
for(const code of ['clv_horizon','synthetic_validation','predetermined_significance','predetermined_clusters','test_variable_alignment']) assert.ok(findings.some(f=>f.code===code),code);
for(const f of findings) if(f.start!==null) assert.equal(method.slice(f.start,f.end),f.evidence);
assert.equal(A.preflight('Estimaremos el CLV con retención y descuento.').findings.length,0);
assert.ok(A.preflight('Texto.',{rubric:'Debe incluir análisis.'}).findings.some(f=>f.code==='rubric_manual_check'&&f.start===null));
assert.equal(S.blocks('Introducción\t3')[0].kind,'toc');
const native='Marco conceptual\nContenido real.';
assert.equal(S.blocks(native,{blocks:[{kind:'heading',start:0,end:16,text:'Marco conceptual'}]})[0].kind,'heading');
for(const b of S.blocks(native)) assert.equal(native.slice(b.start,b.end),b.text);
console.log('Academic v3: multi-author references, stage-aware preflight, advisory evidence and structure spans passed.');
const fs=require('node:fs'),vm=require('node:vm');
(async()=>{
 const raw='Introducción\n\nContenido.';
 const heading={textContent:'Introducción',tagName:'H1',matches:()=>false,closest:()=>null};
 const paragraph={textContent:'Contenido.',tagName:'P',matches:()=>false,closest:()=>null};
 const context=vm.createContext({ZeroIARules:globalThis.ZeroIARules,DOMParser:class{parseFromString(){return {querySelectorAll:()=>[heading,paragraph]};}},window:{mammoth:{extractRawText:async()=>({value:raw,messages:[]}),convertToHtml:async()=>({value:'<h1>Introducción</h1><p>Contenido.</p>'})}}});
 vm.runInContext(fs.readFileSync('js/document-parser.js','utf8'),context);
 const file={name:'test.docx',size:100,arrayBuffer:async()=>new ArrayBuffer(8)};
 const result=await context.window.ZeroIAParser.extractTextFromFile(file);
 assert.equal(result.text,raw);
 assert.equal(result.extraction.structure.mapped,2);
 for(const b of result.extraction.structure.blocks) assert.equal(raw.slice(b.start,b.end),b.text);
 context.window.mammoth.convertToHtml=async()=>{throw Error('unsupported');};
 const fallback=await context.window.ZeroIAParser.extractTextFromFile(file);
 assert.equal(fallback.text,raw);
 assert.ok(fallback.extraction.warnings.some(w=>w.includes('no se pudo conservar')));
 console.log('DOCX parser: canonical raw text, mapped structure and recoverable HTML failure passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});

const stale={blocks:[{kind:'heading',start:0,end:16,text:'Marco conceptual'}]};
assert.equal(S.blocks('Texto corregido!\nContenido real.',stale)[0].kind,'body');
assert.equal(S.blocks(native,{blocks:[{kind:'heading',start:0,end:16}]})[0].kind,'body');
const nested='# Introducción\n## Contexto\nEl contenido del apartado.\n# Resultados';
const emptyFindings=A.preflight(nested,{stage:'final'}).findings.filter(f=>f.code==='empty_section');
assert.equal(emptyFindings.length,1);
assert.equal(emptyFindings[0].evidence,'# Resultados');
const separated='Se utilizarán datos sintéticos.\nObjetivo: demostrar la validez empírica del modelo.';
const synthetic=A.preflight(separated).findings.find(f=>f.code==='synthetic_validation');
assert.ok(synthetic);
assert.equal(separated.slice(synthetic.start,synthetic.end),synthetic.evidence);
assert.equal(synthetic.related_evidence.text,'Se utilizarán datos sintéticos.');
assert.equal(A.preflight('Los datos sintéticos permiten una simulación.').findings.filter(f=>f.code==='synthetic_validation').length,0);
