"""Generate the browser/Node rules bundle; --check fails on stale generated rules."""
import json
from pathlib import Path
import sys
root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'config/editorial-rules.json').read_text())
content = '// Generated by tools/build_rules.py; edit config/editorial-rules.json.\n' + 'globalThis.ZeroIARules = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n'
target = root / 'js/editorial-rules.js'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != content:
        raise SystemExit('Rules bundle is stale: run python tools/build_rules.py')
else:
    target.write_text(content)
